app/views/track.py
from app.models import User
from flask import Blueprint, render_template
from flask.ext.login import login_required, current_user

mod = Blueprint('track', __name__)

@mod.route('/user/<string:username>')
def user(username):
    u = User.query.filter_by(username=username).first_or_404()
    return render_template('track/user.html', posts=list(u.posts), username=u.username)

@mod.route('/me')
@login_required
def me():
    return user(current_user.username)

@mod.route('/following')
@login_required
def following():
    # TODO: to be continued ...
    return render_template('404.html')

@mod.route('/')
def index():
    return render_template('track/index.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% from "forms/macros.html" import render_link %}

{% block title %}Mega Tracker - 1984 {% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">
                    Track-It
                </a>
            </div>

            <div class="navbar-left">
                <p class="navbar-text">
                    {{ render_link("track.index", "Home") }}
                </p>
                <p class="navbar-text">
                    <a href="{{ url_for("track.me") }}">Me</a>
                </p>
                {% if current_user.role == 1 %}
                    <p class="navbar-text">
                        <a href="/admin">Admin</a>
                    </p>
                {% endif %}
            </div>

            <div class="navbar-right">
                {% if current_user.is_authenticated() %}
                    <p class="navbar-text">
                        Signed in as {{ current_user.username }}
                    </p>
                    <p class="navbar-text">
                        {{ render_link("user.settings", "Settings") }}
                    </p>
                    <p class="navbar-text">
                        {{ render_link("user.logout", "Logout") }}
                    </p>

                {% else %}
                    <p class="navbar-text">
                        {{ render_link("user.login", "Login") }}
                    </p>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}
{% block content %}

<div class="container">
    {% import "bootstrap/utils.html" as utils %}
    {{ utils.flashed_messages() }}
</div>

{% endblock %}